spring.application.name=sonics

spring.datasource.url=jdbc:postgresql://localhost:5433/sonics
spring.datasource.username=postgres
spring.datasource.password=1939
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true